class demolocate():
    Sign_up_ID = "signin2"
    Username_ID = "sign-username"
    Password_ID = "sign-password"
    Sign_up_XP = "//button"  # 5
    Close_XP = "//button"  # 5
    Log_in_LT = "Log in"
    Username2_ID = "loginusername"
    Password2_ID = "loginpassword"
    Log_in_XP = "//button"  # 8
    # Phone_LT = "Nokia lumia 1520"
    phone_XP = "//div/h4/a"  # 1
    Addtocart_LT = "Add to cart"
    Cartbtn_ID = "cartur"
    Checkcart_XP = "//td"  # 1
    logout_ID = "logout2"
    button_XP = "//button"  # 29
    name_ID = "name"
    country_ID = "country"
    city_ID = "city"
    Creditcard_ID = "card"
    Month_ID = "month"
    Year_ID = "year"
    Purchase_XP = "//button"  # 8
    Thanks_XP = "//h2"  # 2
    Laptop_LT = "Laptops"
    Sony_LT = "Sony vaio i5"
    sony_Head_XP = "//h2"
    Monitors_LT = "Monitors"
    Apple_LT = "Apple monitor 24"
    moni_head_XP = "//h2"
